#!/bin/bash
# GOATd Kernel Build - Initialize Asset Caching
#
# This script configures intelligent asset caching (SRCDEST) and compiler
# caching (ccache) to speed up kernel rebuilds.
#
# Usage:
#   ./scripts/setup-caching.sh [--aggressive] [--help]
#
# Options:
#   --aggressive : Set up aggressive caching (larger cache sizes)
#   --help       : Show this help message
#
# Environment:
#   SRCDEST      : Override source cache directory (default: /tmp/kernel-sources)
#   CCACHE_DIR   : Override ccache directory (default: ~/.cache/ccache)
#   CCACHE_MAXSIZE : Set ccache maximum size (default: 10G for aggressive, 5G normal)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Default configuration
SRCDEST="${SRCDEST:-/tmp/kernel-sources}"
CCACHE_DIR="${CCACHE_DIR:-$HOME/.cache/ccache}"
AGGRESSIVE_MODE=false
CCACHE_MAXSIZE="5G"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --aggressive)
            AGGRESSIVE_MODE=true
            CCACHE_MAXSIZE="50G"
            shift
            ;;
        --help|-h)
            grep "^#" "$0" | head -20
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║     GOATd Kernel Build - Asset Caching Setup                       ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

# ============================================================================
# SECTION 1: Check System Requirements
# ============================================================================
echo "📋 Checking system requirements..."

if ! command -v makepkg &> /dev/null; then
    echo "❌ ERROR: makepkg not found. Install 'base-devel' package:"
    echo "   sudo pacman -S base-devel"
    exit 1
fi
echo "✅ makepkg found"

if command -v ccache &> /dev/null; then
    echo "✅ ccache installed (version: $(ccache --version | head -1))"
    CCACHE_AVAILABLE=true
else
    echo "⚠️  ccache not installed. Install for faster rebuilds:"
    echo "   sudo pacman -S ccache"
    CCACHE_AVAILABLE=false
fi

echo ""

# ============================================================================
# SECTION 2: Create Source Cache Directory
# ============================================================================
echo "📁 Setting up source cache directory..."
echo "   SRCDEST=$SRCDEST"

if mkdir -p "$SRCDEST"; then
    chmod 755 "$SRCDEST"
    echo "✅ Source cache directory ready"
    
    # Show existing cached files
    if [ -d "$SRCDEST" ] && [ -n "$(find "$SRCDEST" -maxdepth 1 -type f 2>/dev/null | head -1)" ]; then
        echo ""
        echo "   📦 Cached sources found:"
        ls -lh "$SRCDEST" | tail -n +2 | awk '{printf "      - %s (%s)\n", $9, $5}' | head -10
        local_count=$(find "$SRCDEST" -maxdepth 1 -type f | wc -l)
        if [ "$local_count" -gt 10 ]; then
            echo "      ... and $((local_count - 10)) more files"
        fi
    fi
else
    echo "❌ ERROR: Failed to create source cache directory"
    exit 1
fi

echo ""

# ============================================================================
# SECTION 3: Set Up Compiler Cache (ccache)
# ============================================================================
if $CCACHE_AVAILABLE; then
    echo "⚙️  Setting up compiler cache..."
    echo "   CCACHE_DIR=$CCACHE_DIR"
    echo "   CCACHE_MAXSIZE=$CCACHE_MAXSIZE"
    
    mkdir -p "$CCACHE_DIR"
    chmod 755 "$CCACHE_DIR"
    
    # Export environment variables
    export CCACHE_DIR
    export CCACHE_MAXSIZE
    
    # Configure ccache
    ccache -M "$CCACHE_MAXSIZE" > /dev/null 2>&1 || true
    
    echo "✅ Compiler cache configured"
    
    # Show ccache stats
    echo ""
    echo "   📊 Current ccache statistics:"
    ccache -s | grep -E "^(Max cache|Cache size|Files|Hits|Misses)" | awk '{printf "      %s\n", $0}'
else
    echo "⏭️  Skipping compiler cache (ccache not installed)"
fi

echo ""

# ============================================================================
# SECTION 4: Generate Environment Configuration
# ============================================================================
echo "📝 Generating environment configuration..."

BASH_RC_ADDITIONS="
# ============================================================================
# GOATd Kernel Build Caching Configuration
# Generated by: $SCRIPT_DIR/setup-caching.sh
# Date: $(date)
# ============================================================================

export SRCDEST='$SRCDEST'
export CCACHE_DIR='$CCACHE_DIR'
export CCACHE_MAXSIZE='$CCACHE_MAXSIZE'

# Add ccache to PATH if available
if [ -d /usr/lib/ccache/bin ]; then
    export PATH=\"/usr/lib/ccache/bin:\$PATH\"
fi
"

# Create or update ~/.bashrc
if [ -f "$HOME/.bashrc" ]; then
    # Check if already configured
    if grep -q "GOATd Kernel Build Caching Configuration" "$HOME/.bashrc"; then
        echo "✅ Environment variables already in ~/.bashrc"
    else
        echo "📝 Adding configuration to ~/.bashrc..."
        echo "$BASH_RC_ADDITIONS" >> "$HOME/.bashrc"
        echo "✅ Configuration added"
        echo ""
        echo "⚠️  Please reload your shell:"
        echo "   source ~/.bashrc"
    fi
else
    echo "📝 Creating ~/.bashrc with configuration..."
    echo "$BASH_RC_ADDITIONS" >> "$HOME/.bashrc"
    echo "✅ ~/.bashrc created"
fi

echo ""

# ============================================================================
# SECTION 5: Verify Configuration
# ============================================================================
echo "🔍 Verifying configuration..."

# Check current environment
if [ -z "${SRCDEST:-}" ]; then
    echo "⚠️  SRCDEST not in current shell (need to source ~/.bashrc)"
    SRCDEST_STATUS="not set in current shell"
else
    SRCDEST_STATUS="set to $SRCDEST ✅"
fi

if [ -z "${CCACHE_DIR:-}" ]; then
    if $CCACHE_AVAILABLE; then
        echo "⚠️  CCACHE_DIR not in current shell (need to source ~/.bashrc)"
        CCACHE_STATUS="not set in current shell"
    else
        CCACHE_STATUS="ccache not installed"
    fi
else
    CCACHE_STATUS="set to $CCACHE_DIR ✅"
fi

echo ""

# ============================================================================
# SECTION 6: Configuration Summary
# ============================================================================
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║          🎉 Asset Caching Setup Complete                          ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Configuration Summary:"
echo "   Source Cache (SRCDEST)    : $SRCDEST_STATUS"
if $CCACHE_AVAILABLE; then
    echo "   Compiler Cache (CCACHE_DIR): $CCACHE_STATUS"
    echo "   Max Cache Size            : $CCACHE_MAXSIZE"
fi
echo ""

echo "🚀 Next Steps:"
echo "   1. Source your bash configuration to activate in current shell:"
echo "      source ~/.bashrc"
echo ""
echo "   2. Build the kernel:"
echo "      cd /mnt/Optane/goatd/linux"
echo "      SRCDEST=$SRCDEST makepkg -s"
echo ""
echo "   3. Monitor cache effectiveness:"
if $CCACHE_AVAILABLE; then
    echo "      ccache -s  (show compiler cache statistics)"
fi
echo "      ls -lah $SRCDEST  (show cached sources)"
echo ""

echo "📖 Documentation:"
echo "   See: $PROJECT_DIR/plans/ASSET_CACHING_IMPLEMENTATION.md"
echo "   Example config: $PROJECT_DIR/config/makepkg.conf.example"
echo ""

echo "💡 Tips:"
echo "   - On first build, sources will be downloaded and cached"
echo "   - On subsequent builds, cached sources speed up the process"
if $CCACHE_AVAILABLE; then
    echo "   - Compiler cache provides 50-70% speedup on rebuilds"
    echo "   - Check ccache hit ratio: ccache -s"
fi
echo "   - Clear cache if needed: rm -rf $SRCDEST && ccache -C"
echo ""
